# Generated by Django 4.0.4 on 2022-04-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_period_name', models.CharField(max_length=40)),
                ('period_start_date', models.DateField()),
                ('period_finish_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Періоди творчості',
                'verbose_name_plural': ' Періоди творчості',
            },
        ),
        migrations.CreateModel(
            name='ArtWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Напрямки творчості',
                'verbose_name_plural': 'Напрямки творчості',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_writing', models.DateField()),
                ('notes', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Збірки творів',
                'verbose_name_plural': 'Збірки творів',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Жанри',
                'verbose_name_plural': 'Жанри',
            },
        ),
        migrations.CreateModel(
            name='PoetViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_topic', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': ' Погляди Шевченка ',
                'verbose_name_plural': ' Погляди Шевченка',
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=30)),
                ('start_learning_date', models.DateField()),
                ('end_learning_date', models.DateField()),
                ('notes', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Школи',
                'verbose_name_plural': 'Школи',
            },
        ),
        migrations.CreateModel(
            name='LiteratureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_writing', models.DateField()),
                ('notes', models.CharField(max_length=100)),
                ('art_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shevchenko.artperiod')),
                ('art_way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shevchenko.artway')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shevchenko.collection')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shevchenko.genre')),
            ],
            options={
                'verbose_name': ' Cписок літературних творів',
                'verbose_name_plural': ' Cписок літературних творів',
            },
        ),
        migrations.CreateModel(
            name='ArtList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_writing', models.DateField()),
                ('notes', models.CharField(max_length=300)),
                ('art_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shevchenko.artperiod')),
                ('art_way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shevchenko.artway')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shevchenko.genre')),
            ],
            options={
                'verbose_name': ' Cписок художніх творів',
                'verbose_name_plural': ' Cписок художніх творів',
            },
        ),
    ]
